services:
  db:
    image: mariadb:11
    container_name: cerebrus-db
    environment:
      MARIADB_DATABASE: cerebrus
      MARIADB_USER: cerebrus
      MARIADB_PASSWORD: cerebrus
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: cerebrus-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mariadb://db:3306/cerebrus
      DB_USER: cerebrus
      DB_PASSWORD: cerebrus
    
      GOOGLE_API_KEY_1: ${GEMINI_API_KEY_1}
      GOOGLE_API_KEY_2: ${GEMINI_API_KEY_2}
      GOOGLE_API_KEY_3: ${GEMINI_API_KEY_3}
      GOOGLE_API_KEY_4: ${GEMINI_API_KEY_4}
      GOOGLE_API_KEY_5: ${GEMINI_API_KEY_5}
      brevo.api.key: $${brevo.api.key}
      brevo.sender.email: $${brevo.sender.email}
      brevo.sender.name: $${brevo.sender.name}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  locust:
    image: locustio/locust:2.39.1
    container_name: cerebrus-locust
    depends_on:
      - backend
    working_dir: /mnt/locust
    volumes:
      - ./locust:/mnt/locust
    environment:
      CEREBRUS_USERNAME: ${CEREBRUS_USERNAME:-alumno_harry}
      CEREBRUS_PASSWORD: ${CEREBRUS_PASSWORD:-123456}
      CEREBRUS_MAESTRO_USERNAME: ${CEREBRUS_MAESTRO_USERNAME:-carlos_pro}
      CEREBRUS_MAESTRO_PASSWORD: ${CEREBRUS_MAESTRO_PASSWORD:-123456}
    command:
      - -f
      - /mnt/locust/locustfile.py
      - --host=http://backend:8080
    ports:
      - "8089:8089"

  frontend:
    build: 
      context: ./frontend
      args:
        LOGROCKET_ID: "${LOGROCKET_ID}"
        LOGROCKET_MANUAL_RECORDING: "${LOGROCKET_MANUAL_RECORDING:-true}"
        WATCHBUG_ADMIN: "${WATCHBUG_ADMIN:-false}"
    container_name: cerebrus-frontend
    environment:
        LOGROCKET_ID: "${LOGROCKET_ID}"
        LOGROCKET_MANUAL_RECORDING: "${LOGROCKET_MANUAL_RECORDING:-true}"
        WATCHBUG_ADMIN: "${WATCHBUG_ADMIN:-false}"
    depends_on:
      - backend
    ports:
      - "3000:80"

  watchbug-service:
    build: 
      context: ./watchbug-app
    container_name: watchbug
    ports:
      - "5000:5000"
    environment:
      - WATCHBUG_ENABLED=True
      - WATCHBUG_ADMIN=${WATCHBUG_ADMIN:-false}
      - SENTRY_DSN=${SENTRY_DSN}
      - LOGROCKET_ID=${LOGROCKET_ID}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_BUCKET_NAME=watchbug-screenshots
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}

volumes:
  dbdata:
